# Generated by Django 4.1.6 on 2023-02-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_customuser_regularuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnailsize",
            name="size",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic"),
                    ("PREMIUM", "Premium"),
                    ("ENTERPRISE", "Enterprise"),
                    ("CUSTOM", "Custom"),
                ],
                default="CUSTOM",
                max_length=32,
            ),
        ),
    ]
