# Generated by Django 4.1.6 on 2023-02-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_thumbnailsize_size_alter_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="binary_expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
