# Generated by Django 4.1.6 on 2023-02-20 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_image_binary_expiration_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-uploaded_on"]},
        ),
    ]
